# Generated by Django 6.0.5 on 2026-05-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaSexo',
            fields=[
                ('idSexo', models.AutoField(primary_key=True, serialize=False)),
                ('Sexo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PersonaSexo',
            },
        ),
    ]
