# Generated by Django 6.0.5 on 2026-05-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Cedula', models.CharField(max_length=20)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=20)),
                ('Celular', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=200)),
                ('Direccion', models.CharField(max_length=400)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='fotos_personas/')),
                ('idSexo', models.ForeignKey(db_column='idSexo', on_delete=django.db.models.deletion.CASCADE, to='authentication.personasexo')),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
    ]
