# Generated by Django 6.0.5 on 2026-05-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Nombre',
            new_name='Nombre_Completo',
        ),
    ]
