# Generated by Django 6.0.5 on 2026-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_nombre_persona_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
    ]
