# Generated by Django 6.0.5 on 2026-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
    ]
