# Generated by Django 6.0.5 on 2026-06-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_empresa_delete_empresas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='Empresas',
        ),
    ]
