# Generated by Django 6.0.5 on 2026-06-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_empresa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('idGerencia', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('idEmpresa', models.ForeignKey(db_column='idEmpresa', on_delete=django.db.models.deletion.CASCADE, to='authentication.empresa')),
            ],
            options={
                'db_table': 'Gerencia',
            },
        ),
    ]
