# Generated by Django 6.0.5 on 2026-06-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_gerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(db_column='id_Departamento', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('idGerencia', models.ForeignKey(db_column='idGerencia', on_delete=django.db.models.deletion.CASCADE, to='authentication.gerencia')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
    ]
