# Generated by Django 6.0.5 on 2026-06-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='idDepartamento',
            new_name='id_Departamento',
        ),
    ]
