# Generated by Django 6.0.5 on 2026-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_iddepartamento_departamento_id_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_Departamento',
            field=models.AutoField(db_column='id_Depertamento', primary_key=True, serialize=False),
        ),
    ]
