# Generated by Django 6.0.5 on 2026-06-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('idPuesto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(max_length=150)),
                ('idDepartamento', models.ForeignKey(db_column='id_Depertamento', on_delete=django.db.models.deletion.CASCADE, to='authentication.departamento')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'Puesto',
            },
        ),
    ]
