# Generated by Django 6.0.5 on 2026-06-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={},
        ),
    ]
