# Generated by Django 6.0.5 on 2026-06-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_puesto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensacion_Puesto',
            fields=[
                ('idCompensacion', models.AutoField(primary_key=True, serialize=False)),
                ('Salario_Bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Salario_Sem_Neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Comision_Base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Variable_Base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Viaticos_Alimenticios', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Kilometraje_Base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Bono_Base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Vigencia', models.DateField()),
                ('idPuesto', models.OneToOneField(db_column='idPuesto', on_delete=django.db.models.deletion.CASCADE, to='authentication.puesto')),
            ],
            options={
                'db_table': 'Compensacion_Puesto',
            },
        ),
    ]
