# Generated by Django 6.0.5 on 2026-06-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_compensacion_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idContrato', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Contrato', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Ingreso', models.DateField()),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.AlterModelOptions(
            name='compensacion_puesto',
            options={'ordering': ['-Vigencia']},
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='Bono_Base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='Comision_Base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='Kilometraje_Base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='Variable_Base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='Viaticos_Alimenticios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compensacion_puesto',
            name='idPuesto',
            field=models.ForeignKey(db_column='idPuesto', on_delete=django.db.models.deletion.CASCADE, to='authentication.puesto'),
        ),
        migrations.AddConstraint(
            model_name='compensacion_puesto',
            constraint=models.UniqueConstraint(fields=('idPuesto', 'Vigencia'), name='uq_puesto_vigencia'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='idContrato',
            field=models.ForeignKey(db_column='idContrato', on_delete=django.db.models.deletion.CASCADE, to='authentication.contrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='idPersona',
            field=models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.CASCADE, to='authentication.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='idPuesto',
            field=models.ForeignKey(db_column='idPuesto', on_delete=django.db.models.deletion.CASCADE, to='authentication.puesto'),
        ),
    ]
