# Generated by Django 6.0.5 on 2026-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_contrato_empleado_alter_compensacion_puesto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='Descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
