# Generated by Django 6.0.5 on 2026-06-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_puesto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasante',
            fields=[
                ('id_pasante', models.AutoField(db_column='idPasante', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='Fecha_Fin', null=True)),
                ('universidad', models.CharField(db_column='Univercidad', max_length=200)),
                ('carrera', models.CharField(db_column='Carrera', max_length=200)),
                ('tutor_universitario', models.CharField(db_column='Tutor_Univercitario', max_length=200)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('empleado_supervisor', models.ForeignKey(db_column='idEmpleado_Sup', on_delete=django.db.models.deletion.PROTECT, related_name='pasantes_supervisados', to='authentication.empleado')),
                ('persona', models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.PROTECT, related_name='pasantes', to='authentication.persona')),
                ('puesto', models.ForeignKey(db_column='idPuesto', on_delete=django.db.models.deletion.PROTECT, related_name='pasantes', to='authentication.puesto')),
            ],
            options={
                'verbose_name': 'Pasante',
                'verbose_name_plural': 'Pasantes',
                'db_table': 'Pasante',
            },
        ),
    ]
