# Generated by Django 6.0.5 on 2026-06-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_pasante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasante',
            name='empleado_supervisor',
            field=models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.PROTECT, related_name='pasantes_supervisados', to='authentication.empleado'),
        ),
    ]
