# Generated by Django 6.0.7 on 2026-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_pasante_empleado_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPersonal',
            fields=[
                ('idAccion', models.AutoField(db_column='idAccion', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'Accion_Personal',
                'ordering': ['-Fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccionTipo',
            fields=[
                ('idAccion_Tipo', models.AutoField(db_column='idAccion_Tipo', primary_key=True, serialize=False)),
                ('Detalle', models.CharField(db_column='Detalle', max_length=600)),
                ('Monto_TA', models.DecimalField(blank=True, db_column='Monto_TA', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Acción Tipo',
                'verbose_name_plural': 'Acciones Tipo',
                'db_table': 'Accion_Tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora_Entrada', models.TimeField()),
                ('Hora_Salida', models.TimeField()),
                ('Horas_Extra', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Asistencia',
                'ordering': ['-Fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEstado',
            fields=[
                ('idAsis_Estado', models.AutoField(primary_key=True, serialize=False)),
                ('TipoEstado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Asistencia_Estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CausaSalida',
            fields=[
                ('idCausa', models.AutoField(db_column='idCausa', primary_key=True, serialize=False)),
                ('Causa', models.CharField(db_column='Causa', max_length=150)),
                ('Categoria', models.CharField(db_column='Categoria', max_length=80)),
            ],
            options={
                'verbose_name': 'Causa de Salida',
                'verbose_name_plural': 'Causas de Salida',
                'db_table': 'Causa_Salida',
                'ordering': ['Categoria', 'Causa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuadrante9Box',
            fields=[
                ('idCuadrante_9box', models.AutoField(db_column='idCuadrante_9box', primary_key=True, serialize=False)),
                ('Cuadrante', models.IntegerField(db_column='Cuadrante')),
            ],
            options={
                'verbose_name': 'Cuadrante 9 Box',
                'verbose_name_plural': 'Cuadrantes 9 Box',
                'db_table': 'Cuadrante_9box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuadrante9BoxDesempeno',
            fields=[
                ('idCuadrante_9box_Desempeno', models.AutoField(db_column='idCuadrante_9box_Desempeno', primary_key=True, serialize=False)),
                ('Nivel_Desempeno', models.CharField(db_column='Nivel_Desempeno', max_length=18)),
            ],
            options={
                'verbose_name': 'Nivel de Desempeño',
                'verbose_name_plural': 'Niveles de Desempeño',
                'db_table': 'Cuadrante_9box_Desempeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuadrante9BoxPerfil',
            fields=[
                ('idCuadrante_9box_Perfil', models.AutoField(db_column='idCuadrante_9box_Perfil', primary_key=True, serialize=False)),
                ('Tipo_Profecional', models.CharField(db_column='Tipo_Profecional', max_length=80)),
                ('Perfil', models.CharField(db_column='Perfil', max_length=500)),
            ],
            options={
                'verbose_name': 'Perfil 9 Box',
                'verbose_name_plural': 'Perfiles 9 Box',
                'db_table': 'Cuadrante_9box_Perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuadrante9BoxPotencial',
            fields=[
                ('idCuadrante_9box_Potencial', models.AutoField(db_column='idCuadrante_9box_Potencial', primary_key=True, serialize=False)),
                ('Nivel_Potencial', models.CharField(db_column='Nivel_Potencial', max_length=1)),
            ],
            options={
                'verbose_name': 'Nivel de Potencial',
                'verbose_name_plural': 'Niveles de Potencial',
                'db_table': 'Cuadrante_9box_Potencial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleAccion',
            fields=[
                ('id_Detalle_Accion', models.AutoField(db_column='id_Detalle_Accion', primary_key=True, serialize=False)),
                ('Accion', models.CharField(db_column='Accion', max_length=80)),
            ],
            options={
                'db_table': 'Detalle_Accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_Estatus_Vacante', models.AutoField(db_column='id_Estatus_Vacante', primary_key=True, serialize=False)),
                ('TipoEstatus', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'db_table': 'Estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(db_column='idEvaluacion', primary_key=True, serialize=False)),
                ('Fecha_Evaluacion', models.DateField(db_column='Fecha_Evaluacion')),
            ],
            options={
                'db_table': 'Evaluacion',
                'ordering': ['-Fecha_Evaluacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id_desempeno', models.AutoField(db_column='id_Desempeno', primary_key=True, serialize=False)),
                ('cumple_metas_objetivos', models.BooleanField(db_column='Cumple_Metas_Objetivos')),
                ('cumple_funciones_asig', models.BooleanField(db_column='Cumple_FuncionesAsig')),
                ('entregables_calidad_tiempo', models.BooleanField(db_column='Entregables_Calidad_Tiempo')),
                ('cumple_asistencia', models.BooleanField(db_column='Cumple_Asistencia')),
                ('muestra_compromiso_colaboracion', models.BooleanField(db_column='Muestra_Compromiso_Colaboracion')),
                ('pct_total_ev', models.DecimalField(blank=True, db_column='pct_totalEv', decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=500)),
            ],
            options={
                'db_table': 'Evaluacion_Desempeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionJefePotencial',
            fields=[
                ('id_Eva_JefePote', models.AutoField(db_column='id_Eva_JefePote', primary_key=True, serialize=False)),
                ('Capacidad_Liderazgo', models.BooleanField(db_column='Capacidad_Liderazgo')),
                ('Aprendizaje_Rapido', models.BooleanField(db_column='Aprendizaje_Rapido')),
                ('Adaptacion_Cambio', models.BooleanField(db_column='Adaptacion_Cambio')),
                ('Iniciativa_Mejora', models.BooleanField(db_column='Iniciativa_Mejora')),
                ('Madurez_Emocional', models.BooleanField(db_column='Madurez_Emocional')),
                ('pct_totalEv', models.DecimalField(blank=True, db_column='pct_totalEv', decimal_places=2, max_digits=12, null=True)),
                ('Observaciones', models.CharField(db_column='Observaciones', max_length=500)),
            ],
            options={
                'db_table': 'Evaluacion_JefePotencial',
                'ordering': ['-id_Eva_JefePote'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaseCandidato',
            fields=[
                ('id_Fase', models.AutoField(db_column='id_Fase', primary_key=True, serialize=False)),
                ('Fase_Actual', models.CharField(db_column='Fase_Actual', max_length=25)),
            ],
            options={
                'db_table': 'FaseCandidato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpiCabecera',
            fields=[
                ('id_KPI', models.AutoField(db_column='id_KPI', primary_key=True, serialize=False)),
                ('mes', models.IntegerField(db_column='Mes')),
                ('anio', models.IntegerField(db_column='Anio')),
            ],
            options={
                'db_table': 'KPI_Cabecera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpiCategoria',
            fields=[
                ('id_KPI_Categoria', models.AutoField(db_column='id_KPI_Categoria', primary_key=True, serialize=False)),
                ('tipo_categoria', models.CharField(db_column='TipoCategoria', max_length=150)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
            ],
            options={
                'db_table': 'KPI_Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpiDetalle',
            fields=[
                ('id_KPI_Detalle', models.AutoField(db_column='id_KPI_Detalle', primary_key=True, serialize=False)),
                ('pct_Alcanzado', models.DecimalField(db_column='pct_Alcanzado', decimal_places=2, max_digits=5)),
                ('Monto_Base', models.DecimalField(db_column='Monto_Base', decimal_places=2, max_digits=12)),
                ('Monto_Total', models.DecimalField(db_column='Monto_Total', decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de KPI',
                'verbose_name_plural': 'Detalles de KPIs',
                'db_table': 'KPI_Detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id_Offboarding', models.AutoField(db_column='id_Offboarding', primary_key=True, serialize=False)),
                ('Fecha_Salida', models.DateField(db_column='Fecha_Salida')),
                ('Descrip_Causa', models.TextField(db_column='Descrip_Causa')),
            ],
            options={
                'verbose_name': 'Offboarding',
                'verbose_name_plural': 'Offboardings',
                'db_table': 'Offboarding',
                'ordering': ['-Fecha_Salida'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffboardingCatalogo',
            fields=[
                ('idCatalogo', models.AutoField(db_column='idCatalogo', primary_key=True, serialize=False)),
                ('Num_Etapa', models.PositiveSmallIntegerField(db_column='Num_Etapa')),
                ('Etapa', models.CharField(db_column='Etapa', max_length=80)),
                ('Actividad', models.CharField(db_column='Actividad', max_length=300)),
            ],
            options={
                'verbose_name': 'Actividad del Catálogo Offboarding',
                'verbose_name_plural': 'Actividades del Catálogo Offboarding',
                'db_table': 'Offboarding_Catalogo',
                'ordering': ['Num_Etapa', 'idCatalogo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffboardingChecklist',
            fields=[
                ('id_Check', models.AutoField(db_column='id_Check', primary_key=True, serialize=False)),
                ('Fecha_Asignacion', models.DateField(blank=True, db_column='Fecha_Asignacion', editable=False, null=True)),
                ('Fecha_Comp', models.DateField(blank=True, db_column='Fecha_Comp', null=True)),
                ('Observacion', models.CharField(blank=True, db_column='Observacion', max_length=500, null=True)),
                ('pct_listo', models.DecimalField(db_column='pct_listo', decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Checklist de Offboarding',
                'verbose_name_plural': 'Checklists de Offboarding',
                'db_table': 'Offboarding_Checklist',
                'ordering': ['-Fecha_Asignacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffboardingChecklistDetalle',
            fields=[
                ('idDetalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('Fecha_Actualizacion', models.DateTimeField(blank=True, db_column='Fecha_Actualizacion', editable=False, null=True)),
                ('Completado', models.BooleanField(db_column='Completado', default=False)),
            ],
            options={
                'verbose_name': 'Detalle del Checklist',
                'verbose_name_plural': 'Detalles del Checklist',
                'db_table': 'Offboarding_Checklist_Detalle',
                'ordering': ['idCatalogo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnActividad',
            fields=[
                ('idActividad', models.AutoField(db_column='idActividad', primary_key=True, serialize=False)),
                ('Actividad', models.CharField(db_column='Actividad', max_length=300)),
            ],
            options={
                'verbose_name': 'Actividad de Onboarding',
                'verbose_name_plural': 'Actividades de Onboarding',
                'db_table': 'On_Actividad',
                'ordering': ['Actividad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id_Onboarding', models.AutoField(db_column='id_Onboarding', primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateField(db_column='Fecha_Inicio')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboardings',
                'db_table': 'Onboarding',
                'ordering': ['-Fecha_Inicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingActividad',
            fields=[
                ('id_Detalle_On', models.AutoField(db_column='id_Detalle_On', primary_key=True, serialize=False)),
                ('Fecha_Programada', models.DateField(db_column='Fecha_Programada')),
                ('Fecha_Realizada', models.DateField(db_column='Fecha_Realizada')),
                ('Observaciones', models.CharField(db_column='Observaciones', max_length=600)),
            ],
            options={
                'verbose_name': 'Actividad de Onboarding',
                'verbose_name_plural': 'Actividades de Onboarding',
                'db_table': 'Onboarding_Actividad',
                'ordering': ['Fecha_Programada'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idPeriodo', models.AutoField(db_column='idPeriodo', primary_key=True, serialize=False)),
                ('Tipo_Periodo', models.CharField(db_column='Tipo_Periodo', max_length=30)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'Periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idPermiso', models.AutoField(db_column='idPermiso', primary_key=True, serialize=False)),
                ('Activo', models.BooleanField(db_column='Activo', default=True)),
                ('Justificacion', models.CharField(db_column='Justificacion', max_length=5000)),
            ],
            options={
                'db_table': 'Permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('idPremio', models.AutoField(db_column='idPremio', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('Alcance', models.CharField(db_column='Alcance', max_length=200)),
                ('Monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'db_table': 'Premio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PremioAsignado',
            fields=[
                ('id_PremioAsignado', models.AutoField(db_column='id_PremioAsignado', primary_key=True, serialize=False)),
                ('Monto_Liquidado', models.DecimalField(db_column='Monto_Liquidado', decimal_places=2, max_digits=12)),
                ('Fecha_Registro', models.DateField(db_column='Fecha_Registro')),
            ],
            options={
                'verbose_name': 'Premio Asignado',
                'verbose_name_plural': 'Premios Asignados',
                'db_table': 'Premio_Asignado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoFase',
            fields=[
                ('id_Proceso', models.AutoField(db_column='id_Proceso', primary_key=True, serialize=False)),
                ('Resultado_Av', models.CharField(db_column='Resultado_Av', max_length=80)),
            ],
            options={
                'db_table': 'ProcesoFase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('TipoRol', models.CharField(db_column='TipoRol', max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['TipoRol'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RotacionPersonal',
            fields=[
                ('idRotacion', models.AutoField(db_column='idRotacion', primary_key=True, serialize=False)),
                ('Anio', models.PositiveSmallIntegerField(db_column='Anio')),
                ('Mes', models.PositiveSmallIntegerField(blank=True, db_column='Mes', null=True)),
                ('A_Contratados', models.PositiveIntegerField(db_column='A_Contratados')),
                ('D_Desvinculados', models.PositiveIntegerField(db_column='D_Desvinculados')),
                ('D_Jubilaciones_Defuncionales', models.PositiveIntegerField(db_column='D_Jubilaciones_Defuncionales')),
                ('D_Total_Bajas', models.PositiveIntegerField(db_column='D_Total_Bajas')),
                ('F1_Inicio', models.PositiveIntegerField(db_column='F1_Inicio')),
                ('F2_Final', models.PositiveIntegerField(db_column='F2_Final')),
                ('IRP', models.DecimalField(db_column='IRP', decimal_places=2, max_digits=5)),
                ('IRP_Sugerido_Min', models.DecimalField(db_column='IRP_Sugerido_Min', decimal_places=2, max_digits=5)),
                ('IRP_Sugerido_Max', models.DecimalField(db_column='IRP_Sugerido_Max', decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Rotación de Personal',
                'verbose_name_plural': 'Rotaciones de Personal',
                'db_table': 'Rotacion_Personal',
                'ordering': ['-Anio', '-Mes'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalarioEmpleado',
            fields=[
                ('idSalarioEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField(blank=True, null=True)),
                ('Salario_Bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Salario_Sem_Neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Comision_Base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Variable_Base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Viaticos_Alimenticios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Kilometraje_Base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Bono_Base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Compensacion_Total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('Observaciones', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Salario Empleado',
                'verbose_name_plural': 'Salarios Empleados',
                'db_table': 'Salario_Empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id_TipoPermiso', models.AutoField(db_column='id_TipoPermiso', primary_key=True, serialize=False)),
                ('Tipo_Permiso', models.CharField(db_column='Tipo_Permiso', max_length=80)),
            ],
            options={
                'db_table': 'TipoPermiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnionMatrizEmp',
            fields=[
                ('id_Matriz', models.AutoField(db_column='id_Matriz', primary_key=True, serialize=False)),
                ('Anio', models.IntegerField(db_column='Anio')),
                ('Plan_Accion', models.TextField(db_column='Plan_Accion')),
            ],
            options={
                'verbose_name': 'Matriz 9 Box',
                'verbose_name_plural': 'Matrices 9 Box',
                'db_table': 'Union_Matriz_Emp',
                'ordering': ['-Anio', '-id_Matriz'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id_Admin', models.AutoField(db_column='id_Admin', primary_key=True, serialize=False)),
                ('Correo', models.EmailField(db_column='Correo', max_length=200)),
                ('Contrasenia', models.CharField(db_column='Contrasenia', max_length=128)),
                ('Activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'UsuarioSistema',
                'ordering': ['Correo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacacionSaldo',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False)),
                ('Anio', models.IntegerField()),
                ('Dias_Acumulados', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Dias_Tomado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Dias_Disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'Vacacion_Saldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacacionSolicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Solicitud', models.DateField()),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Dias_Solicitud', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'Vacacion_Solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id_Vacante', models.AutoField(db_column='id_Vacante', primary_key=True, serialize=False)),
                ('Fecha_Registro', models.DateField()),
                ('TituloPublicacion', models.CharField(max_length=150)),
                ('Motivo', models.CharField(max_length=200)),
                ('Expe_Requerida', models.CharField(max_length=500)),
                ('Salario_Bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Compensacion_Total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Cierre_Proceso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Vacante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante_Asig',
            fields=[
                ('id_Vacante_Asig', models.AutoField(db_column='id_Vacante_Asig', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Asignación de Vacante',
                'verbose_name_plural': 'Asignaciones de Vacantes',
                'db_table': 'Vacante_Asig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante_Candidato',
            fields=[
                ('id_Candidato', models.AutoField(primary_key=True, serialize=False)),
                ('Activo', models.BooleanField(default=True)),
                ('Observaciones', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Vacante_Candidato',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='compensacion_puesto',
            options={'managed': False, 'ordering': ['-Vigencia']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pasante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personasexo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'managed': False},
        ),
    ]
